zeo:
  image: plone-imio:latest
  user: imio
  mem_limit: 2024m
  volumes:
      - var/blobstorage:/home/imio/imio-website/var/blobstorage
      - var/filestorage:/home/imio/imio-website/var/filestorage
  command: /home/imio/imio-website/bin/zeoserver fg
instance:
  image: plone-imio:latest
  user: imio
  mem_limit: 2024m
  ports:
    - "8081:8081"
  links:
    - zeo:db
  environment:
    - ZEO_HOST=db
    - ZEO_PORT=8100
    - HOSTNAME_HOST=local
    - PROJECT_ID=imiotest
    - MEMCACHE_SERVER=127.0.0.1
  command: /home/imio/imio-website/bin/instance console
