version: '3.4'
services:
  zeo:
    image: docker-staging.imio.be/cpskin.test:${uid}
    user: plone
    volumes:
        - .:/home/plone/website
    working_dir: /home/plone/website
    command: /home/plone/website/bin/zeoserver fg
  instance:
    image: docker-staging.imio.be/cpskin.test:${uid}
    user: plone
    ports:
      - "8081:8081"
    links:
      - zeo:db
    volumes:
      - .:/home/plone/website
    working_dir: /home/plone/website
    environment:
      - MEMCACHE_SERVER=127.0.0.1
      - MEMCACHE_DEFAULT_AGE=10800
      - ENV=dev
      - CACHING_SERVERS=http://frontend1.interne.imio.be:5000 http://frontend2.lan.imio.be:5000 http://frontend3.lan.imio.be:5000
      - DOMAINS=localhost
      - ZEO_HOST=db
      - ZEO_PORT=8100
    command: /home/plone/website/bin/instance fg
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
