FROM docker-staging.imio.be/iasmartweb/test:1000
RUN mkdir /home/imio/imio-website/
COPY *.cfg /home/imio/imio-website/
COPY *.txt /home/imio/imio-website/
RUN chown imio:imio -R /home/imio/imio-website/
COPY docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh
RUN chown imio:imio /docker-entrypoint.sh
WORKDIR /home/imio/imio-website
USER imio
RUN virtualenv -p python2.7 . && bin/pip install -r requirements.txt && bin/buildout
ENTRYPOINT ["/docker-entrypoint.sh"]
