version: '3.4'
services:
  zeo:
    image: docker-staging.imio.be/iasmartweb/test:${uid}
    user: imio
    volumes:
        - .:/home/imio/imio-website
    working_dir: /home/imio/imio-website
    command: /home/imio/imio-website/bin/zeoserver fg
  instance:
    image: docker-staging.imio.be/iasmartweb/test:${uid}
    user: imio
    ports:
      - "8081:8081"
    links:
      - zeo:db
    volumes:
      - .:/home/imio/imio-website
    working_dir: /home/imio/imio-website
    environment:
      - MEMCACHE_SERVER=127.0.0.1
      - MEMCACHE_DEFAULT_AGE=10800
      - ENV=dev
      - CACHING_SERVERS=http://frontend1.interne.imio.be:5000 http://frontend2.lan.imio.be:5000 http://frontend3.lan.imio.be:5000
      - DOMAINS=localhost
      - ZEO_HOST=db
      - ZEO_PORT=8100
    command: /home/imio/imio-website/bin/instance fg
