FROM docker-staging.imio.be/base:latest
RUN usermod -u 1000 imio
RUN groupmod -g 1000 imio
# RUN find / -user 913 -exec chown -h 1000 {} \;
# RUN find / -group 209 -exec chgrp -h 1000 {} \;
RUN usermod -g 1000 imio
RUN mkdir /home/imio/imio-website
COPY *.cfg /home/imio/imio-website/
COPY Makefile /home/imio/imio-website/
COPY *.py /home/imio/imio-website/
COPY scripts /home/imio/imio-website/scripts
RUN chown imio:imio -R /home/imio/imio-website/
WORKDIR /home/imio/imio-website
RUN apt-get -qy install build-essential rsync gcc python27 python27-virtualenv python27-setuptools libxml2-dev libxslt1-dev zlib1g-dev libjpeg-dev lynx wv poppler-utils git
USER imio
RUN make buildout-cache/downloads
RUN /opt/python2.7.8/bin/python bootstrap.py -c docker-dev.cfg
RUN make buildout-docker-dev
ENV HOME /home/imio/imio-website
ENV HTTP_PORT=8081
ENV ZEO_HOST db
ENV ZEO_PORT 8100
ENV HOSTNAME_HOST localhost
ENV PROJECT_ID imiolocal
