zeo:
  build: .
  user: imio
  mem_limit: 2024m
  volumes:
      - var/blobstorage:/home/imio/imio-website/var/blobstorage
      - var/filestorage:/home/imio/imio-website/var/filestorage
  command: /home/imio/imio-website/bin/zeoserver fg
instance:
  build: .
  user: imio
  mem_limit: 2024m
  # memswap_limit: 0m # integrate in docker-compose >= 1.4
  ports:
    - "8081:8081"
  links:
    - zeo:db
  volumes:
    - .:/home/imio/imio-website/
  environment:
    - ZEO_HOST=db
    - ZEO_PORT=8100
    - HOSTNAME_HOST=local
    - PROJECT_ID=imiotest
    - MEMCACHE_SERVER=127.0.0.1
  command: /home/imio/imio-website/bin/instance console
