FROM docker-staging.imio.be/iasmartweb/test:1000
RUN mkdir /home/imio/imio-website/
ENV PATH="/home/imio/.local/bin:${PATH}"
COPY *.cfg /home/imio/imio-website/
COPY *.txt /home/imio/imio-website/
RUN chown imio:imio -R /home/imio/imio-website/
COPY docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh
RUN chown imio:imio /docker-entrypoint.sh
WORKDIR /home/imio/imio-website
USER imio
RUN rm -rf /home/imio/.local &&  rm -rf /home/imio/.cache && pip install --user -r requirements.txt && buildout -c docker-dev.cfg
ENTRYPOINT ["/docker-entrypoint.sh"]
