#!/bin/sh
set -x
set -e

PACKAGE="imio-website"
PACKAGE_HOME="/home/imio/$PACKAGE"

case "$1" in
    configure)
	# create var
	/bin/chown -R imio.imio $PACKAGE_HOME
	/bin/chmod 0700 $PACKAGE_HOME/var/blobstorage
	/bin/chmod 0700 $PACKAGE_HOME/var/filestorage
    ;;

    abort-remove|abort-upgrade|abort-deconfigure)
        echo "abort"
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
