#!/bin/sh
set -e
set -x

PACKAGE="imio-website-core"


case "$1" in
    remove|deconfigure)
	find /home/imio/imio-website/eggs -name "*.pyc" -delete;
	find /home/imio/imio-website/eggs -name "*.pyo" -delete;
	find /home/imio/imio-website/eggs -name "*.bin" -delete;
	find /home/imio/imio-website/eggs -name "*.mo" -delete;
    ;;

    upgrade|failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

exit 0
