#!/bin/sh

set -e

PACKAGE="imio-website"


case "$1" in
    remove|deconfigure)
    if [ -f /etc/init.d/$PACKAGE ]; then
      /usr/sbin/service $PACKAGE stop >/dev/null 2>&1

      /bin/rm -f /etc/init.d/$PACKAGE >/dev/null 2>&1

      /usr/sbin/update-rc.d $PACKAGE remove >/dev/null 2>&1

      rm -f /etc/logrotate.d/$PACKAGE >/dev/null 2>&1
    fi
    ;;

    upgrade|failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
